// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuQmR19a3zOEcnBpFP3yv162AETXOT4Ac',
    appId: '1:778938433937:web:3ddbacc7d6a92015eeda30',
    messagingSenderId: '778938433937',
    projectId: 'finance-tracker-app-75b32',
    authDomain: 'finance-tracker-app-75b32.firebaseapp.com',
    storageBucket: 'finance-tracker-app-75b32.firebasestorage.app',
    measurementId: 'G-B9ESLMH9PN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADyAcs-FPPBtWkV1AzrG4_rYoZl0tFL08',
    appId: '1:778938433937:android:9d8f7ef1806513d3eeda30',
    messagingSenderId: '778938433937',
    projectId: 'finance-tracker-app-75b32',
    storageBucket: 'finance-tracker-app-75b32.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDJKRMW3Y_lYnPx0E2CFXOZGZnivg5uWg',
    appId: '1:778938433937:ios:69b62882507a5f6aeeda30',
    messagingSenderId: '778938433937',
    projectId: 'finance-tracker-app-75b32',
    storageBucket: 'finance-tracker-app-75b32.firebasestorage.app',
    iosBundleId: 'com.intern.test.financeTrackerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDJKRMW3Y_lYnPx0E2CFXOZGZnivg5uWg',
    appId: '1:778938433937:ios:69b62882507a5f6aeeda30',
    messagingSenderId: '778938433937',
    projectId: 'finance-tracker-app-75b32',
    storageBucket: 'finance-tracker-app-75b32.firebasestorage.app',
    iosBundleId: 'com.intern.test.financeTrackerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDuQmR19a3zOEcnBpFP3yv162AETXOT4Ac',
    appId: '1:778938433937:web:039aa2108ca1bbeaeeda30',
    messagingSenderId: '778938433937',
    projectId: 'finance-tracker-app-75b32',
    authDomain: 'finance-tracker-app-75b32.firebaseapp.com',
    storageBucket: 'finance-tracker-app-75b32.firebasestorage.app',
    measurementId: 'G-91F4562RHR',
  );

}